[package]
name         = "cyd-player"
edition      = "2024"
version      = "0.1.0"
rust-version = "1.93"
license      = "GPL-3.0-or-later"

[[bin]]
name = "cyd-video"
path = "./src/bin/main.rs"

[features]
default = ["log"]
log = [
    "esp-hal/log-04",
    "esp-rtos/log-04",
    "esp-bootloader-esp-idf/log-04",
    "esp-println/log-04",
    "embedded-sdmmc/log",
    "embassy-executor/log",
    "embassy-time/log",
    "embassy-sync/log",
    "embassy-futures/log",
]
embed-video = []

[build-dependencies]
bindgen = "0.72.1"

[dependencies]
esp-hal = { version = "~1.1.0", features = ["esp32s3", "unstable"] }
esp-rtos = { version = "0.3.0", features = [
  "esp32s3",
  "embassy",
  "esp-alloc",
] }
esp-bootloader-esp-idf = { version = "0.5.0", features = ["esp32s3"] }
esp-backtrace = { version = "0.19.0", features = [
  "esp32s3",
  "panic-handler",
  "println",
] }
esp-println = { version = "0.17.0", features = ["esp32s3"] }
esp-alloc = "0.10.0"
log = "0.4.27"
embassy-executor = "0.10.0"
embassy-time = "0.5.0"
embassy-sync = "0.8.0"
embassy-futures = "0.1.2"
critical-section = "1.2.0"
static_cell      = "2.1.1"

embedded-hal-bus = "0.3.0"
embedded-hal = "1.0.0"
mipidsi = "0.9.0"
es8311 = "0.1.1"
embedded-graphics = "0.8.1"
# XXX Custom embedded-sdmmc to avoid infinite recursion
# https://github.com/rust-embedded-community/embedded-sdmmc-rs/commit/a707d3094ea7c54e38d4e0e278e1a638bda62ba1
embedded-sdmmc = { git = "https://github.com/rust-embedded-community/embedded-sdmmc-rs.git", rev="ce5710f", default-features = false }
embedded-io = "0.7"  # match embedded-sdmmc
format_no_std = "1.2.0"
riffparse = { git = "https://github.com/rectalogic/riffparse.git", tag = "0.5.0", default-features = false, features = ["embedded-io"] }
thiserror = { version = "2.0.18", default-features = false }

[lints.clippy]
# mem::forget is generally not safe to do with esp_hal types, especially those holding buffers for the duration of a data transfer.
mem_forget = "deny"

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units    = 1     # LLVM can perform better optimizations using a single thread
debug            = 2
debug-assertions = false
incremental      = false
lto              = 'fat'
opt-level        = 's'
overflow-checks  = false
