name: Player CI

on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: true
      - name: Setup Rust
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          buildtargets: "esp32,esp32s3"
          ldproxy: false
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Run checks
        run: |
          cargo fmt --all -- --check
          cargo clippy --target xtensa-esp32-none-elf -- -D warnings
          cargo clippy --target xtensa-esp32s3-none-elf -- -D warnings
