name: Player CI

on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AVI_DIRECTORY: AVI

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        esp_chip: ["esp32", "esp32s3"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: true
      - name: Setup Rust
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          buildtargets: ${{ matrix.esp_chip }}
          ldproxy: false
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Run checks
        run: |
          cargo fmt --all -- --check
          cargo clippy --features ${{ matrix.esp_chip }} -- -D warnings
